services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8088:8080"

  postgres_ticket:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: bondstone
      POSTGRES_DB: ticket_service
    ports:
      - "5433:5432"

  postgres_comment:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: bondstone
      POSTGRES_DB: comment_service
    ports:
      - "5434:5432"

  postgres_user:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: bondstone
      POSTGRES_DB: user_service
    ports:
      - "5435:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ticket-service:
    build: ./ticket-service
    depends_on: [postgres_ticket, keycloak, kafka, redis]
    environment:
      SERVER_PORT: 8080
      DB_URL: jdbc:postgresql://postgres_ticket:5432/ticket_service
      DB_USER: root
      DB_PASS: bondstone
      KC_ISSUER: http://keycloak:8080/realms/miniTicket
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP: kafka:9092
    ports:
      - "8080:8080"

  comment-service:
    build: ./comment-service
    depends_on: [postgres_comment, keycloak, kafka]
    environment:
      SERVER_PORT: 8081
      DB_URL: jdbc:postgresql://postgres_comment:5432/comment_service
      DB_USER: root
      DB_PASS: bondstone
      KC_ISSUER: http://keycloak:8080/realms/miniTicket
      KAFKA_BOOTSTRAP: kafka:9092
    ports:
      - "8081:8081"

  user-service:
    build: ./user-service
    depends_on: [postgres_user, keycloak]
    environment:
      SERVER_PORT: 8083
      DB_URL: jdbc:postgresql://postgres_user:5432/user_service
      DB_USER: root
      DB_PASS: bondstone
      KC_ISSUER: http://keycloak:8080/realms/miniTicket
    ports:
      - "8083:8083"

  api-gateway:
    build: ./api-gateway
    depends_on: [ticket-service, comment-service, user-service, keycloak]
    environment:
      SERVER_PORT: 9001
      KC_ISSUER: http://keycloak:8080/realms/miniTicket
    ports:
      - "9001:9001"
