server:
  port: 9001

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ticket-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/tickets/**

        - id: comment-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/comments/**

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/users/**
