
services:
  postgresdb:
    image: postgres:15
    container_name: postgresComment
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: bondstone
      POSTGRES_DB: comment_service
    volumes:
      - ./data:/var/lib/postgresql/data
