version: '4.43.1'
services:
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: bondstone
      POSTGRES_DB: ticket_service
    volumes:
      - ./data:/var/lib/postgresql/data
